#!/usr/bin/env python3
# -*- coding: utf-8 -*-


from datetime import date, timedelta
import json
from urllib.request import Request, urlopen


import pandas as pd

monitor_url = 'https://monitor.uruguaysevacuna.gub.uy/plugin/cda/api/doQuery?'



def get_data(data, columns):
    json_origin = json.loads(urlopen(Request(monitor_url, data=data)).read().decode())
    return pd.DataFrame(json_origin["resultset"], columns=columns).fillna(0)




start_data = date(2021,3,1)

end_data = date(2021,5,9)

delta = timedelta(days=1)
while start_data <= end_data:
    print (start_data.strftime("%Y-%m-%d"))
    dia = start_data.strftime("%Y-%m-%d")    
    today_str = bytes(dia.replace("-", "").encode())
    data = b"paramp_periodo_desde_sk=" + today_str + b"&paramp_periodo_hasta_sk=" + \
       today_str + b"&paramp_rango_tipo=7&" \
                  b"path=%2Fpublic%2FEpidemiologia%2FVacunas+Covid%2FPaneles%2FVacunas+Covid%2F" \
                  b"VacunasCovid.cda&dataAccessId=sql_vacunas_rango_edad&" \
                  b"outputIndexId=1&pageSize=0&pageStart=0&" \
                      b"sortBy=&paramsearchBox="
    result = get_data(data, ['age', 'value'])   
    result['fecha'] = start_data
    result.to_csv('vacunasXDia.csv',mode='a',header=False)
    start_data += delta